### PR TITLE
add safwanyp to team.csv

### PR DESCRIPTION
**Pull request by safwanyp**
- Hourly rate is 840 SEK (Swedish Kronor) which can be converted to around 75 USD.
- For https://github.com/opensourcepledge/opensourcepledge.com/pull/220 I can confidently say that I spent no more than 3 hours (initial exploration before creating the PR limited to just the issue, then the PR).
- I was thinking of billing for 2.5 hours if you support increments other than hourly, or just 2 hours if hourly increments are expected.

Let me know 😁

### CODE REVIEW

**Comment by chadwhitacre** [comment]
This looks great to me, thanks @safwanyp. Will wait for a review from @vladh as well.

Let's land the [increments conversation](https://github.com/opensourcepledge/opensourcepledge.com/issues/226#issuecomment-2444168978) on #226.

**Comment by chadwhitacre** [comment]
Woo-hoo! Welcome aboard, @safwanyp! 😁 💃

**Comment by safwanyp** [comment]
Thank you!!

**Comment by safwanyp** [comment]
@chadwhitacre @vladh 
Does this mean I can create an issue with an invoice, or do we tackle that as you guys iron things out?

**Comment by chadwhitacre** [comment]
@safwanyp Yes, go ahead and create an issue with an invoice. I am about to sign off for the weekend so I will pick up with getting your and @vladh's invoices paid and making sure we have good visibility into finances next week.

**Pull request merged**
